# Run the server
run *args:
    cd {{justfile_directory()}} && node src/main.js {{args}}

# Run tests
test *args:
    cd {{justfile_directory()}} && node --test src/**/*.test.js {{args}}

# Reset database
reset:
    rm -f {{justfile_directory()}}/pinpoint.db
