inputs:
  - path: ../../sample_library/memories
    root: memories
  - path: ../../sample_library/music
    root: music
  - path: ../../sample_library/movies
    root: movies
  - path: ../../sample_library/tv
    root: tv
  - path: ../../sample_library/podcasts
    root: podcasts
  - path: ../../sample_library/books
    root: books
  - path: ../../sample_library/comedy
    root: comedy

output: ../../sample_output
data_dir: .data
